set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10)

set(CMAKE_C_COMPILER cl.exe)
set(CMAKE_CXX_COMPILER cl.exe)
set(CMAKE_RC_COMPILER rc.exe)

set(CMAKE_GENERATOR_TOOLSET "v143" CACHE STRING "MSVC toolset" FORCE)

if(NOT DEFINED CMAKE_GENERATOR_PLATFORM OR CMAKE_GENERATOR_PLATFORM STREQUAL "")
    set(CMAKE_GENERATOR_PLATFORM "x64" CACHE STRING "MSVC target architecture")
endif()

set(_SWG_ALLOWED_GENERATOR_PLATFORMS Win32 x64)
list(FIND _SWG_ALLOWED_GENERATOR_PLATFORMS "${CMAKE_GENERATOR_PLATFORM}" _SWG_GENERATOR_PLATFORM_INDEX)
if(_SWG_GENERATOR_PLATFORM_INDEX EQUAL -1)
    message(
        FATAL_ERROR
        "Unsupported CMAKE_GENERATOR_PLATFORM='${CMAKE_GENERATOR_PLATFORM}'. "
        "Expected one of: Win32, x64."
    )
endif()

set(SWG_PLATFORM_NAME "windows-msvc")
