set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10)

set(CMAKE_C_COMPILER cl.exe)
set(CMAKE_CXX_COMPILER cl.exe)
set(CMAKE_RC_COMPILER rc.exe)

set(CMAKE_GENERATOR_TOOLSET "v143" CACHE STRING "MSVC toolset" FORCE)

set(SWG_PLATFORM_NAME "windows-msvc")
