[CmdletBinding()]
param(
    [ValidateSet('Release', 'Optimized', 'Debug')]
    [string]$Configuration = 'Release',

    [ValidateSet('win32', 'win64')]
    [string]$Architecture = 'win64',

    [ValidateSet('native', 'dxvk')]
    [string]$Runtime = 'native',

    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,

    [string[]]$ClientOutputDirs = @(),

    [switch]$FailIfDxvkMissing
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$rendererProjects = @('Direct3d9', 'Direct3d9_ffp', 'Direct3d9_vsps')
$compileRoot = Join-Path $RepositoryRoot (Join-Path 'src\compile' $Architecture)
$otherArchitecture = if ($Architecture -eq 'win32') { 'win64' } else { 'win32' }
$otherCompileRoot = Join-Path $RepositoryRoot (Join-Path 'src\compile' $otherArchitecture)
$dxvkArchFolder = if ($Architecture -eq 'win32') { 'x86' } else { 'x64' }
$dxvkDll = Join-Path $RepositoryRoot (Join-Path 'src\external\3rd\dxvk\2.4' (Join-Path $dxvkArchFolder 'd3d9.dll'))

function Write-DxvkConfigFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$TargetPath,

        [switch]$AmdProfile
    )

    $profileLines = @(
        "# Auto-generated by package-win32-renderers.ps1 for DXVK packaging ($Architecture).",
        '# Delete this file to use DXVK defaults.',
        '# Override location by setting DXVK_CONFIG_FILE=<path>.',
        ''
    )

    if ($AmdProfile) {
        $profileLines += @(
            '# AMD profile (VendorId 0x1002): conservative frame pacing defaults for D3D9 workloads.',
            'd3d9.presentInterval = 1',
            'd3d9.maxFrameLatency = 1',
            '# Async can reduce stutter but may surface content hazards on legacy paths.',
            'dxvk.enableAsync = False',
            'dxgi.maxFrameLatency = 1'
        )
    } else {
        $profileLines += @(
            '# Generic profile (non-AMD): conservative D3D9 defaults.',
            'd3d9.presentInterval = 1',
            'd3d9.maxFrameLatency = 2',
            'dxvk.enableAsync = False'
        )
    }

    Set-Content -Path $TargetPath -Value ($profileLines -join "`r`n") -Encoding ASCII
}

function Get-RendererDllCount {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BaseCompileRoot
    )

    $count = 0
    foreach ($project in $rendererProjects) {
        $sourceDir = Join-Path $BaseCompileRoot (Join-Path $project $Configuration)
        if (-not (Test-Path $sourceDir)) {
            continue
        }

        $count += (Get-ChildItem -Path $sourceDir -Filter '*.dll' -File | Measure-Object).Count
    }

    return $count
}

if (-not $ClientOutputDirs -or $ClientOutputDirs.Count -eq 0) {
    $ClientOutputDirs = @(
        (Join-Path $compileRoot (Join-Path 'SwgClient' $Configuration)),
        (Join-Path $compileRoot (Join-Path 'SwgClientSetup' $Configuration))
    )
}

$normalizedCompileRoot = [System.IO.Path]::GetFullPath($compileRoot)
$normalizedOtherCompileRoot = [System.IO.Path]::GetFullPath($otherCompileRoot)
for ($i = 0; $i -lt $ClientOutputDirs.Count; $i++) {
    $normalizedTarget = [System.IO.Path]::GetFullPath($ClientOutputDirs[$i])
    if ($normalizedTarget.StartsWith($normalizedOtherCompileRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Client output target '$normalizedTarget' points at '$otherArchitecture'. Refusing cross-architecture packaging for '$Architecture'."
    }

    $ClientOutputDirs[$i] = $normalizedTarget
}

$rendererDllCountForArch = Get-RendererDllCount -BaseCompileRoot $compileRoot
$rendererDllCountForOtherArch = Get-RendererDllCount -BaseCompileRoot $otherCompileRoot
if ($rendererDllCountForArch -eq 0 -and $rendererDllCountForOtherArch -gt 0) {
    throw "No renderer DLLs found under '$compileRoot' for '$Architecture', but found $rendererDllCountForOtherArch under '$otherCompileRoot'. Refusing cross-architecture packaging."
}

if ($Runtime -eq 'dxvk' -and -not (Test-Path $dxvkDll)) {
    $otherDxvkArchFolder = if ($dxvkArchFolder -eq 'x86') { 'x64' } else { 'x86' }
    $otherDxvkDll = Join-Path $RepositoryRoot (Join-Path 'src\external\3rd\dxvk\2.4' (Join-Path $otherDxvkArchFolder 'd3d9.dll'))
    if (Test-Path $otherDxvkDll) {
        throw "DXVK runtime file for '$Architecture' is missing: $dxvkDll. Found only '$otherDxvkDll'; refusing cross-architecture packaging."
    }
}

$resolvedTargets = [System.Collections.Generic.List[string]]::new()
foreach ($project in $rendererProjects) {
    $target = Join-Path $compileRoot (Join-Path $project $Configuration)
    $resolvedTargets.Add($target)
}
foreach ($target in $ClientOutputDirs) {
    $resolvedTargets.Add($target)
}

$rendererCopied = 0
foreach ($project in $rendererProjects) {
    $sourceDir = Join-Path $compileRoot (Join-Path $project $Configuration)
    if (-not (Test-Path $sourceDir)) {
        Write-Warning "Renderer output folder not found: $sourceDir"
        continue
    }

    $rendererDlls = Get-ChildItem -Path $sourceDir -Filter '*.dll' -File
    foreach ($target in $ClientOutputDirs) {
        New-Item -ItemType Directory -Path $target -Force | Out-Null
        foreach ($rendererDll in $rendererDlls) {
            Copy-Item -Path $rendererDll.FullName -Destination (Join-Path $target $rendererDll.Name) -Force
            $rendererCopied++
        }
    }
}

Write-Host "Copied $rendererCopied renderer DLL(s) into client output directory targets."

if ($Runtime -eq 'dxvk') {
    if (-not (Test-Path $dxvkDll)) {
        $message = "DXVK runtime file is missing: $dxvkDll"
        if ($FailIfDxvkMissing) {
            throw $message
        }

        Write-Warning "$message (skipping DXVK copy because -FailIfDxvkMissing was not set)."
        return
    }

    foreach ($target in $resolvedTargets) {
        New-Item -ItemType Directory -Path $target -Force | Out-Null
        Copy-Item -Path $dxvkDll -Destination (Join-Path $target 'd3d9.dll') -Force
        Write-DxvkConfigFile -TargetPath (Join-Path $target 'dxvk.conf')
    }

    Write-Host "DXVK runtime enabled. Copied d3d9.dll ($dxvkArchFolder) and generated dxvk.conf in $($resolvedTargets.Count) output target(s)."
} else {
    foreach ($target in $resolvedTargets) {
        $nativeDll = Join-Path $target 'd3d9.dll'
        if (Test-Path $nativeDll) {
            Remove-Item -Path $nativeDll -Force
        }

        $dxvkConfig = Join-Path $target 'dxvk.conf'
        if (Test-Path $dxvkConfig) {
            Remove-Item -Path $dxvkConfig -Force
        }
    }

    Write-Host "Native runtime selected. Removed local d3d9.dll and dxvk.conf overrides from output targets."
}
